ISSUE: Rust just saved us from potential disaster
What we are trying to do is the following:
The main thread sends slices of float arrays to each of the worker
threads, then the worker threads send the slices back.

However, what happens if the main thread dies? i.e.  thread::spawn
outlives the lifetime of Game?   Then the backing memory of the slice
is not managed by anyone anymore! but the threads can still access it!
This sounds very unsafe, and luckily, rust throws a nice obscure error!

It even gives a nice solution: Why not give game a static lifetime?
that way we know its memory will never be freed until exit of the
program

╰─$ cargo build                                                                         101 ↵
   Compiling pathtracer v0.1.0 (file:///home/arian/Documents/UU/MCPD/pathtracer)
error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements
   --> src/main.rs:122:9
    |
122 |         Ok(game)
    |         ^^^^^^^^
    |
note: first, the lifetime cannot outlive the lifetime 'a as defined on the block at 93:91...
   --> src/main.rs:93:92
    |
93  |     fn new(width: usize, height: usize, num_workers: usize) -> Result<Game<'a>, io::Error> {
    |                                                                                            ^
note: ...so that types are compatible (expected std::result::Result<Game<'a>, std::io::Error>, found std::result::Result<Game<'_>, std::io::Error>)
   --> src/main.rs:122:9
    |
122 |         Ok(game)
    |         ^^^^^^^^
    = note: but, the lifetime must be valid for the static lifetime...
note: ...so that the type `[closure@src/main.rs:108:45: 112:14 tx:std::sync::mpsc::Sender<GameMsg<'_>>, rx:spmc::Receiver<WorkerMsg<'_>>]` will meet its required lifetime bounds
   --> src/main.rs:108:31
    |
108 |             workers.push(Some(thread::spawn(move || {
    |                               ^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `pathtracer`.

To learn more, run the command again with --verbose.