ISSUE tried to implement texture render but got borrow error
   Compiling pathtracer v0.1.0 (file:///home/arian/Documents/UU/MCPD/pathtracer)
warning: unnecessary parentheses around `if` condition, #[warn(unused_parens)] on by default
  --> src/main.rs:73:12
   |
73 |         if (self.camera.handle_input(&key_presses)) {
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0502]: cannot borrow `self` as immutable because `self.texture` is also borrowed as mutable
   --> src/main.rs:91:38
    |
91  |         self.texture.with_lock(None, |buffer: &mut [u8], pitch: usize| {
    |         ------------                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ immutable borrow occurs here
    |         |
    |         mutable borrow occurs here
...
95  |                     let rgb = vec_to_rgb(scale*self.accumulator.buf[x+y*self.accumulator.width as usize]);
    |                                                ---- borrow occurs due to use of `self` in closure
...
102 |             }).expect("mutate texture");
    |              - mutable borrow ends here

error[E0502]: cannot borrow `self` as immutable because `self.texture` is also borrowed as mutable
   --> src/main.rs:91:38
    |
91  |         self.texture.with_lock(None, |buffer: &mut [u8], pitch: usize| {
    |         ------------                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ immutable borrow occurs here
    |         |
    |         mutable borrow occurs here
...
95  |                     let rgb = vec_to_rgb(scale*self.accumulator.buf[x+y*self.accumulator.width as usize]);
    |                                                ---- borrow occurs due to use of `self` in closure
...
102 |             }).expect("mutate texture");
    |              - mutable borrow ends here

error[E0502]: cannot borrow `self` as immutable because `self.texture` is also borrowed as mutable
   --> src/main.rs:91:38
    |
91  |         self.texture.with_lock(None, |buffer: &mut [u8], pitch: usize| {
    |         ------------                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ immutable borrow occurs here
    |         |
    |         mutable borrow occurs here
...
95  |                     let rgb = vec_to_rgb(scale*self.accumulator.buf[x+y*self.accumulator.width as usize]);
    |                                                ---- borrow occurs due to use of `self` in closure
...
102 |             }).expect("mutate texture");
    |              - mutable borrow ends here

error[E0502]: cannot borrow `self` as immutable because `self.texture` is also borrowed as mutable
   --> src/main.rs:91:38
    |
91  |         self.texture.with_lock(None, |buffer: &mut [u8], pitch: usize| {
    |         ------------                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ immutable borrow occurs here
    |         |
    |         mutable borrow occurs here
...
95  |                     let rgb = vec_to_rgb(scale*self.accumulator.buf[x+y*self.accumulator.width as usize]);
    |                                                ---- borrow occurs due to use of `self` in closure
...
102 |             }).expect("mutate texture");
    |              - mutable borrow ends here

error: aborting due to 4 previous errors

error: Could not compile `pathtracer`.

To learn more, run the command again with --verbose.