ISSUE We cannot set the lifetime of the material field in intersection for some reasons.
   Compiling pathtracer v0.1.0 (file:///home/arian/Documents/UU/MCPD/pathtracer)
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter 'a in generic type due to conflicting requirements
  --> src/primitive/sphere.rs:36:5
   |
36 |     fn intersect<'a>(&'a self, ray: &mut Ray<'a>) -> bool {
   |     ^
   |
help: consider using an explicit lifetime parameter as shown: fn intersect<'b, 'a>(&'a self, ray: &'b mut Ray<'a>) -> bool
  --> src/primitive/sphere.rs:36:5
   |
36 |     fn intersect<'a>(&'a self, ray: &mut Ray<'a>) -> bool {
   |     ^

error[E0495]: cannot infer an appropriate lifetime for lifetime parameter 'a in generic type due to conflicting requirements
  --> src/primitive/triangle.rs:43:5
   |
43 |     fn intersect<'a>(&'a self, ray: &'a mut Ray<'a>) -> bool {
   |     ^
   |
help: consider using an explicit lifetime parameter as shown: fn intersect<'b, 'a>(&'a self, ray: &'a mut Ray<'a>) -> bool
  --> src/primitive/triangle.rs:43:5
   |
43 |     fn intersect<'a>(&'a self, ray: &'a mut Ray<'a>) -> bool {
   |     ^

error: aborting due to 2 previous errors

error: Could not compile `pathtracer`.

To learn more, run the command again with --verbose.